---
name: Shellcheck
on:
  pull_request:
jobs:
  lint:
    name: Lint
    # These permissions are needed to:
    # - Checkout the Git repo (`contents: read`)
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-shellcheck@5ebd09ddbe2ebb471646ce234c6c8dd18663ca7c # v1.30.0
        with:
          reporter: github-pr-check
          fail_level: warning
          level: warning
